services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: acrdb
      POSTGRES_USER: acruser
      POSTGRES_PASSWORD: acrpass
    volumes: [dbdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U acruser -d acrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports: ["80:80","443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [web]
    restart: unless-stopped

volumes:
  dbdata:
  caddy_data:
  caddy_config:
