# Override para produção com Nginx
services:
  web:
    env_file:
      - .env.prod

  nginx:
    env_file:
      - .env.prod
    # Em produção, usar certificados Let's Encrypt
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/staticfiles:ro
      - media_data:/app/media:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    env_file:
      - .env.prod
