# Generated by Django 5.2.5 on 2025-09-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_modality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='event',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID do evento no Google Calendar', max_length=255, null=True, verbose_name='ID Google Calendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='google_calendar_sync_enabled',
            field=models.BooleanField(default=True, help_text='Se deve sincronizar com Google Calendar', verbose_name='Sincronização Google Calendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.instructor'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_google_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização Google'),
        ),
        migrations.AddField(
            model_name='event',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.modality'),
        ),
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Google Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Google Client Secret')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Token Expiry')),
                ('sync_enabled', models.BooleanField(default=False, verbose_name='Sincronização Ativa')),
                ('auto_sync_events', models.BooleanField(default=True, verbose_name='Auto-Sincronizar Eventos')),
                ('sync_interval_hours', models.PositiveIntegerField(default=1, verbose_name='Intervalo Sincronização (horas)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('sync_errors', models.TextField(blank=True, verbose_name='Erros de Sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_config', to='core.organization')),
            ],
            options={
                'verbose_name': 'Configuração Google Calendar',
                'verbose_name_plural': 'Configurações Google Calendar',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('event_create', 'Criar Evento'), ('event_update', 'Atualizar Evento'), ('event_delete', 'Eliminar Evento'), ('calendar_create', 'Criar Calendário'), ('full_sync', 'Sincronização Completa')], max_length=20, verbose_name='Tipo de Sincronização')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('pending', 'Pendente')], default='pending', max_length=10, verbose_name='Estado')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='ID Evento Google')),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, verbose_name='ID Calendário Google')),
                ('sync_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Sincronização')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'verbose_name': 'Log Sincronização Google Calendar',
                'verbose_name_plural': 'Logs Sincronização Google Calendar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorGoogleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(blank=True, help_text='ID do calendário Google específico do instrutor', max_length=255, verbose_name='ID Calendário Google')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sincronização Ativa')),
                ('calendar_name', models.CharField(blank=True, help_text='Nome do calendário no Google (auto-gerado se vazio)', max_length=100, verbose_name='Nome do Calendário')),
                ('calendar_color', models.CharField(default='#0d6efd', max_length=20, verbose_name='Cor do Calendário')),
                ('share_with_organization', models.BooleanField(default=True, verbose_name='Partilhar com Organização')),
                ('public_calendar', models.BooleanField(default=False, verbose_name='Calendário Público')),
                ('sync_acr_events', models.BooleanField(default=True, verbose_name='Sincronizar Eventos ACR')),
                ('sync_proform_events', models.BooleanField(default=True, verbose_name='Sincronizar Eventos Proform')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('sync_errors', models.TextField(blank=True, verbose_name='Erros de Sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to='core.instructor')),
            ],
            options={
                'verbose_name': 'Calendário Google do Instrutor',
                'verbose_name_plural': 'Calendários Google dos Instrutores',
            },
        ),
    ]
