# Generated by Django 5.2.5 on 2025-09-05 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_googlecalendarsynclog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='booking',
            name='credits_used',
            field=models.PositiveIntegerField(default=1, verbose_name='Créditos Utilizados'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Se foi pago fora do sistema de créditos', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago'),
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription_used',
            field=models.ForeignKey(blank=True, help_text='Subscrição utilizada para esta reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientsubscription'),
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('purchase', 'Compra de Créditos'), ('use', 'Uso de Crédito'), ('refund', 'Reembolso'), ('expire', 'Expiração'), ('transfer', 'Transferência')], max_length=20, verbose_name='Ação')),
                ('credits_amount', models.IntegerField(help_text='Positivo para adicionar, negativo para remover', verbose_name='Quantidade de Créditos')),
                ('credits_before', models.PositiveIntegerField(default=0, verbose_name='Créditos Antes')),
                ('credits_after', models.PositiveIntegerField(default=0, verbose_name='Créditos Depois')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_history', to='core.booking')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to='core.person')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_history', to='core.clientsubscription')),
            ],
            options={
                'verbose_name': 'Histórico de Créditos',
                'verbose_name_plural': 'Histórico de Créditos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_credits', 'Créditos Baixos'), ('subscription_expiring', 'Subscrição a Expirar'), ('payment_overdue', 'Pagamento em Atraso'), ('booking_reminder', 'Lembrete de Reserva'), ('credits_expired', 'Créditos Expirados')], max_length=30, verbose_name='Tipo de Alerta')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('read', 'Lido'), ('dismissed', 'Ignorado')], default='pending', max_length=20, verbose_name='Estado')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados adicionais do alerta', verbose_name='Metadados')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta do Sistema',
                'verbose_name_plural': 'Alertas do Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
