# Generated by Django 5.2.5 on 2025-09-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_cancelled_at_booking_credits_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('group_class', 'Aula de Turma'), ('individual', 'Aula Individual'), ('open_class', 'Aula Aberta')], default='open_class', max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='individual_client',
            field=models.ForeignKey(blank=True, help_text='Cliente individual (para aulas individuais)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_events', to='core.person'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome da Turma')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('max_students', models.PositiveIntegerField(default=10, verbose_name='Máximo de Alunos')),
                ('level', models.CharField(blank=True, help_text='Iniciante, Intermédio, Avançado', max_length=50, verbose_name='Nível')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='core.instructor')),
                ('members', models.ManyToManyField(blank=True, help_text='Clientes inscritos nesta turma', related_name='class_groups', to='core.person')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='core.modality')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['modality', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='class_group',
            field=models.ForeignKey(blank=True, help_text='Turma associada (para aulas de turma)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.classgroup'),
        ),
    ]
