# Generated by Django 5.2.5 on 2025-09-06 03:15

import core.fields
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_event_type_event_individual_client_classgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('segment_query', models.JSONField(default=dict, help_text="Ex: {status:'active', lifecycle_stage:'lead'}")),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Template Jinja/Django para envio.')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=16)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_svg',
            field=models.TextField(blank=True, help_text='Conteúdo SVG para branding no admin e dashboard.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lifecycle_stage',
            field=models.CharField(default='subscriber', help_text='subscriber|lead|member|churn_risk|churned', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='marketing_optin_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='marketing_optin_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='search',
            field=core.fields.OptionalSearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='confirmed', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Person._person_upload_to, verbose_name='Foto'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization', 'created_at'], name='core_bookin_organiz_dbab96_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['organization', 'is_active'], name='core_instru_organiz_10aa05_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organization', 'status'], name='core_person_organiz_7e55dd_idx'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.organization'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='core.person'),
        ),
    ]
