# Generated by Django 5.1.1 on 2025-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_crm_features_patch"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="person",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("organization", "email"), name="unique_person_org_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("organization", "nif"), name="unique_person_org_nif"
            ),
        ),
    ]
