# Generated by Django 5.1.1 on 2025-09-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_person_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="consent_rgpd",
            field=models.BooleanField(default=False),
        ),
    ]
