# Generated by Django 5.1.1 on 2025-12-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_optional_person_search_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmada'), ('waitlist', 'Lista de espera'), ('cancelled', 'Cancelada'), ('no_show', 'Falta'), ('checked_in', 'Check-in')], default='confirmed', max_length=16),
        ),
    ]
