# Generated by Django 6.0.4 on 2026-09-04 10:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_data_integrity_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='core_bookin_organiz_af3514_idx',
            old_name='booking_org_status_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome do Encarregado de Educação'),
        ),
        migrations.AddField(
            model_name='person',
            name='guardian_nif',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIF do Encarregado'),
        ),
        migrations.AddField(
            model_name='person',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone do Encarregado'),
        ),
        migrations.AddField(
            model_name='person',
            name='insurance_expiry',
            field=models.DateField(blank=True, help_text='Data de expiração do seguro desportivo', null=True, verbose_name='Validade do Seguro'),
        ),
        migrations.AddField(
            model_name='person',
            name='insurance_policy',
            field=models.CharField(blank=True, help_text='Número da apólice do seguro desportivo', max_length=100, verbose_name='Apólice de Seguro'),
        ),
        migrations.AddField(
            model_name='person',
            name='medical_certificate_expiry',
            field=models.DateField(blank=True, help_text='Data de expiração do atestado/exame médico', null=True, verbose_name='Validade do Atestado Médico'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='instructors/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Person._person_upload_to, verbose_name='Foto'),
        ),
    ]
