# Generated by Django 6.0.4 on 2026-09-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_athlete_insurance_medical_guardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletes_count', models.PositiveIntegerField(default=0, verbose_name='Atletas Sincronizados')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('warning', 'Aviso / Parcial'), ('error', 'Erro')], default='success', max_length=10, verbose_name='Estado')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Ficheiro / Planilha')),
                ('google_sheet_id', models.CharField(blank=True, max_length=255, verbose_name='ID da Google Sheet')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Sincronização')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sync_logs', to='core.organization')),
            ],
            options={
                'verbose_name': 'Log de Sincronização Google Drive',
                'verbose_name_plural': 'Logs de Sincronização Google Drive',
                'ordering': ['-created_at'],
            },
        ),
    ]
