# Generated by Django 6.0.4 on 2026-09-04 11:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_googledrivesynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolPeriodSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Designação do Fecho')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Receita Bruta Total')),
                ('instructor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remuneração dos Instrutores')),
                ('proform_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Parcela Ginásio Proform SC')),
                ('acr_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Parcela Associação ACR')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado pela Direção'), ('settled', 'Liquidado / Pago')], default='draft', max_length=15, verbose_name='Estado')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Liquidação')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Fecho e Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Emitido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_settlements', to='core.organization')),
            ],
            options={
                'verbose_name': 'Fecho de Contas do Protocolo',
                'verbose_name_plural': 'Fechos de Contas do Protocolo',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
