# Generated by Django 6.0.4 on 2026-09-04 11:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_protocolperiodsettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='ipdj_license_expiry',
            field=models.DateField(blank=True, help_text='Data de validade do título profissional', null=True, verbose_name='Validade da Cédula IPDJ'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='ipdj_license_number',
            field=models.CharField(blank=True, help_text='Ex: Cédula n.º 97575 emitida pelo IPDJ', max_length=50, verbose_name='N.º Cédula / Título Profissional IPDJ'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='ipdj_project_name',
            field=models.CharField(blank=True, help_text='Ex: Protocolo ACR-Proform, Projeto IPDJ Desporto para Todos', max_length=150, verbose_name='Projeto / Enquadramento IPDJ'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_technical_director',
            field=models.BooleanField(default=False, help_text='Indica se o instrutor exerce funções de Diretor Técnico do protocolo ou projeto', verbose_name='Diretor Técnico'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_relationship',
            field=models.CharField(blank=True, help_text='Ex: Pai, Mãe, Cônjuge', max_length=60, verbose_name='Parentesco do Contacto de Emergência'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_consent',
            field=models.BooleanField(default=False, help_text='Autorização para captação e divulgação de fotos/vídeos em treinos', verbose_name='Consentimento de Uso de Imagem'),
        ),
        migrations.AddField(
            model_name='person',
            name='member_category',
            field=models.CharField(choices=[('socio', 'Sócio Praticante (ACR)'), ('nao_socio', 'Não Sócio Praticante')], default='nao_socio', help_text='Enquadramento associativo do praticante na ACR', max_length=20, verbose_name='Categoria de Praticante'),
        ),
        migrations.AddField(
            model_name='person',
            name='regulation_accepted',
            field=models.BooleanField(default=True, help_text='Declaração de conhecimento e aceitação do regulamento da ACR', verbose_name='Regulamento Interno Aceite'),
        ),
        migrations.AddField(
            model_name='resource',
            name='address',
            field=models.CharField(blank=True, help_text='Localização física do pavilhão ou sala', max_length=255, verbose_name='Morada / Localização do Espaço'),
        ),
        migrations.AddField(
            model_name='resource',
            name='cession_entity',
            field=models.CharField(blank=True, default='Município de Celorico de Basto', help_text='Ex: Município de Celorico de Basto, Junta de Freguesia, etc.', max_length=150, verbose_name='Entidade Cedente / Proprietário'),
        ),
        migrations.AddField(
            model_name='resource',
            name='facility_type',
            field=models.CharField(choices=[('municipal_cession', 'Cedência Municipal Gratuita'), ('rented', 'Arrendado / Alugado'), ('owned', 'Instalações Próprias')], default='municipal_cession', help_text='Regime jurídico de utilização deste espaço', max_length=30, verbose_name='Regime de Instalações'),
        ),
        migrations.CreateModel(
            name='ProtocolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acr_official_name', models.CharField(default='ACR - Associação Cultural e Recreativa de Basto (Santa Tecla)', max_length=200, verbose_name='Nome Oficial da Associação')),
                ('acr_nipc', models.CharField(default='510695744', max_length=20, verbose_name='NIPC da ACR')),
                ('acr_address', models.CharField(default='Lugar da Igreja, 4890-526 Basto (Santa Tecla)', max_length=255, verbose_name='Sede da ACR')),
                ('acr_representative_name', models.CharField(default='Paulo Sérgio da Cunha Teixeira', max_length=150, verbose_name='Presidente da Direção da ACR')),
                ('acr_representative_role', models.CharField(default='Presidente da Direção', max_length=100, verbose_name='Cargo do Representante ACR')),
                ('proform_official_name', models.CharField(default='PROFORM - Strength & Conditioning', max_length=200, verbose_name='Designação do Ginásio Parceiro')),
                ('proform_nipc', models.CharField(default='210263601', max_length=20, verbose_name='NIPC do Parceiro')),
                ('proform_address', models.CharField(default='Rua Senhora da Conceição 24, 4890-223 Celorico de Basto', max_length=255, verbose_name='Sede do Parceiro')),
                ('proform_representative_name', models.CharField(default='Daniel Silvério Leite Coelho', max_length=150, verbose_name='Representante do Parceiro')),
                ('proform_representative_role', models.CharField(default='Diretor Técnico', max_length=100, verbose_name='Cargo do Representante Parceiro')),
                ('active_ipdj_project', models.CharField(default='Protocolo de Desportos de Combate e Artes Marciais (ACR & Proform SC)', help_text='Designação do projeto ou candidatura ao IPDJ', max_length=200, verbose_name='Projeto / Enquadramento IPDJ Vigente')),
                ('insurance_company', models.CharField(default='Generali Seguros, S.A.', max_length=120, verbose_name='Companhia Seguradora')),
                ('insurance_policy_number', models.CharField(default='0010189147', max_length=60, verbose_name='N.º da Apólice')),
                ('insurance_product_name', models.CharField(default='AP DESP CULT RECREIO - Ginásios com artes marciais', max_length=150, verbose_name='Produto / Opção da Apólice')),
                ('insurance_policy_start', models.DateField(blank=True, null=True, verbose_name='Início da Vigência')),
                ('insurance_policy_expiry', models.DateField(blank=True, null=True, verbose_name='Renovação Anual / Fim')),
                ('insurance_annual_premium', models.DecimalField(decimal_places=2, default=Decimal('362.82'), help_text='Custo total anual do seguro a ser comparticipado pelo Proform à ACR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prémio Anual do Seguro (€)')),
                ('insurance_base_insured_count', models.PositiveIntegerField(default=25, verbose_name='Número Base de Praticantes Segurados')),
                ('insurance_claim_deadline_days', models.PositiveIntegerField(default=3, verbose_name='Prazo para Participação de Sinistros (dias)')),
                ('capital_death_disability', models.DecimalField(decimal_places=2, default=Decimal('33500.00'), max_digits=10, verbose_name='Capital Morte / Invalidez Permanente (€)')),
                ('capital_treatment', models.DecimalField(decimal_places=2, default=Decimal('5500.00'), max_digits=10, verbose_name='Capital Despesas de Tratamento (€)')),
                ('treatment_deductible', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=10, verbose_name='Franquia Despesas Tratamento (€)')),
                ('capital_funeral', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=10, verbose_name='Capital Despesas de Funeral (€)')),
                ('broker_name', models.CharField(default='SPR AGENTE SEGUROS LDA', max_length=150, verbose_name='Mediador de Seguros')),
                ('broker_asf_number', models.CharField(default='4195560913', max_length=50, verbose_name='N.º Registo ASF do Mediador')),
                ('broker_phone', models.CharField(default='963 958 018', max_length=50, verbose_name='Telefone do Mediador')),
                ('broker_address', models.CharField(default='Av. João Pinto Ribeiro 98 Fracção A, 4890-221 Celorico de Basto', max_length=255, verbose_name='Morada do Mediador')),
                ('acr_admin_fee_per_athlete', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Valor fixo mensal a transferir para a ACR por cada praticante ativo nas modalidades', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quota Administrativa ACR por Atleta (€/mês)')),
                ('insurance_split_mode', models.CharField(choices=[('annual_donation', 'Doação Anual Integral (Proform doa prémio à ACR)'), ('monthly_amortization', 'Amortização Mensal Fracionada (1/12 por mês)')], default='monthly_amortization', help_text='Como o custo da apólice é computado nos fechos periódicos', max_length=30, verbose_name='Modo de Repartição do Seguro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_technical_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_protocol_configs', to='core.instructor', verbose_name='Diretor Técnico Ativo')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_config', to='core.organization')),
            ],
            options={
                'verbose_name': 'Parametrização do Protocolo',
                'verbose_name_plural': 'Parametrizações do Protocolo',
            },
        ),
    ]
