# Generated by Django 6.0.4 on 2026-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_instructor_ipdj_license_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Identificador de Série Recorrente'),
        ),
    ]
