# Generated by Django 6.0.4 on 2026-09-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_event_recurrence_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(help_text='Ex: Cinto Branco, Cinto Amarelo (7º Kyu), Cinto Negro 1º Dan', max_length=60, verbose_name='Graduação / Cinto')),
                ('rank_order', models.PositiveIntegerField(default=1, help_text='1=Branco, 2=Amarelo, 3=Laranja, etc.', verbose_name='Ordem do Cinto')),
                ('awarded_date', models.DateField(verbose_name='Data do Exame / Atribuição')),
                ('examiner_name', models.CharField(blank=True, max_length=120, verbose_name='Examinador / Mestre')),
                ('certificate_number', models.CharField(blank=True, max_length=60, verbose_name='N.º de Diploma / Certificado')),
                ('classes_attended_count', models.PositiveIntegerField(default=0, help_text='Aulas contabilizadas no tapete até a este exame', verbose_name='Treinos Cumpridos')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Avaliação Técnica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Graduação / Exame de Cinto',
                'verbose_name_plural': 'Graduações / Exames de Cinto',
                'ordering': ['-awarded_date', '-rank_order'],
            },
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('board', 'Direção'), ('general_assembly', 'Mesa da Assembleia Geral'), ('fiscal_council', 'Conselho Fiscal')], default='board', max_length=30, verbose_name='Órgão Social')),
                ('term_label', models.CharField(default='2024–2028', max_length=60, verbose_name='Mandato')),
                ('start_date', models.DateField(verbose_name='Data de Início / Posse')),
                ('end_date', models.DateField(verbose_name='Data de Término do Mandato')),
                ('election_date', models.DateField(blank=True, null=True, verbose_name='Data da Eleição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mandato em Funções')),
                ('electoral_minutes_ref', models.CharField(blank=True, help_text='Ex: Ata n.º 12/2024 da Assembleia Eleitoral', max_length=120, verbose_name='Referência da Ata Eleitoral')),
                ('notes', models.TextField(blank=True, verbose_name='Observações / Competências Estatutárias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Órgão Social',
                'verbose_name_plural': 'Órgãos Sociais',
                'ordering': ['body_type', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GoverningBodyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Nome do Titular')),
                ('role', models.CharField(max_length=80, verbose_name='Cargo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordem de Precedência')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Titular de Órgão Social',
                'verbose_name_plural': 'Titulares de Órgãos Sociais',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Data em que foi admitido como sócio da ACR', null=True, verbose_name='Data de Admissão de Sócio'),
        ),
        migrations.AddField(
            model_name='person',
            name='current_belt',
            field=models.CharField(blank=True, help_text='Ex: Cinto Branco, Cinto Amarelo (7º Kyu), Cinto Negro 1º Dan', max_length=60, verbose_name='Cinto / Graduação Atual'),
        ),
        migrations.AddField(
            model_name='person',
            name='member_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Número sequencial oficial de associado da ACR', null=True, verbose_name='Número de Sócio ACR'),
        ),
        migrations.AddField(
            model_name='person',
            name='membership_fee_status',
            field=models.CharField(choices=[('up_to_date', 'Quotas em Dia'), ('overdue', 'Quotas em Dívida'), ('exempt', 'Isento de Quotas')], default='up_to_date', max_length=20, verbose_name='Estado das Quotas'),
        ),
        migrations.AddField(
            model_name='person',
            name='qr_code_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token seguro único para leitura de QR Code no cartão e quiosque', max_length=64, null=True, unique=True, verbose_name='Token QR Check-in'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organization', 'member_number'], name='core_person_organiz_3c98c3_idx'),
        ),
        migrations.AddField(
            model_name='athletegraduation',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_graduations', to='core.instructor'),
        ),
        migrations.AddField(
            model_name='athletegraduation',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='core.modality'),
        ),
        migrations.AddField(
            model_name='athletegraduation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='core.organization'),
        ),
        migrations.AddField(
            model_name='athletegraduation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduations', to='core.person'),
        ),
        migrations.AddField(
            model_name='governingbody',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governing_bodies', to='core.organization'),
        ),
        migrations.AddField(
            model_name='governingbodymember',
            name='governing_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.governingbody'),
        ),
        migrations.AddField(
            model_name='governingbodymember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governing_roles', to='core.person'),
        ),
        migrations.AddIndex(
            model_name='athletegraduation',
            index=models.Index(fields=['organization', 'person'], name='core_athlet_organiz_224359_idx'),
        ),
        migrations.AddIndex(
            model_name='athletegraduation',
            index=models.Index(fields=['person', 'modality'], name='core_athlet_person__0e8300_idx'),
        ),
    ]
