# Generated by Django 6.0.4 on 2026-09-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_athletegraduation_governingbody_governingbodymember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entity_affiliation',
            field=models.CharField(choices=[('acr_only', 'Associação ACR'), ('proform_only', 'ProForm'), ('both', 'Ambos (Administração Geral)')], default='both', help_text='Entidade à qual o utilizador pertence: ACR, Proform ou Ambos', max_length=20, verbose_name='Afiliação Institucional'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='color',
            field=models.CharField(blank=True, default='#0d6efd', help_text='Cor hexadecimal para o Gantt', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador Total'), ('acr_direction', 'Direção Associação ACR'), ('acr_staff', 'Staff Associação ACR'), ('proform_director', 'Direção Técnica ProForm'), ('proform_staff', 'Staff ProForm'), ('instructor', 'Instrutor ProForm'), ('staff', 'Staff Geral'), ('client', 'Cliente / Sócio')], default='client', max_length=20, verbose_name='Tipo de Utilizador'),
        ),
    ]
