# Generated by Django 6.0.4 on 2026-09-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.campaign'),
        ),
    ]
